#!/usr/bin/env python3
"""Generate authenticated exact data for the Spotlight 2 Lean certificate."""

from __future__ import annotations

import argparse
import functools
import gzip
import hashlib
import json
import math
import sys
from fractions import Fraction
from pathlib import Path

sys.set_int_max_str_digits(0)

EXPECTED_SHA256 = "04440bb9d0239a68ed38b7d780462380c2b698fdf54f0917c628ff7df35b9826"
EXPECTED_WEIGHT_SHA256 = "a59cf51fe04f8e2868b90ba611dbdf2150a14cf9f9c5fe897c49c3adef96e819"

LEFT = Fraction(
    10994725169666489265372696986380479953059,
    5549682385733169916106039287298646519682,
)
RIGHT = Fraction(49528623466503, 25000000000000)

# Leaves of an adaptive dyadic subdivision of [RIGHT, 500].  Lean checks every
# resulting Bernstein coefficient; these path indices are only compact data.
INTERVAL_LEAVES = [
    (0, 6), (1, 6), (1, 5), (1, 4), (2, 4), (3, 4), (2, 3),
    (12, 5), (26, 6), (27, 6), (7, 4), (32, 6), (132, 8),
    (2128, 12), (4258, 13), (8518, 14), (17038, 15), (17039, 15),
    (1065, 11), (533, 10), (267, 9), (67, 7), (34, 6), (140, 8),
    (564, 10), (2260, 12), (2261, 12), (1131, 11), (283, 9),
    (71, 7), (9, 4), (5, 3), (3, 2),
]


def lean_rat(value: str | Fraction) -> str:
    q = value if isinstance(value, Fraction) else Fraction(value)
    if q.denominator == 1:
        return f"({q.numerator} : ℚ)"
    return f"({q.numerator} : ℚ) / {q.denominator}"


def wrapped_array(name: str, values: list[str], ty: str = "ℚ", width: int = 100) -> str:
    lines = [f"def {name} : Array {ty} := #["]
    current = "  "
    for i, value in enumerate(values):
        token = value + ("," if i + 1 < len(values) else "")
        if len(current) > 2 and len(current) + len(token) + 1 > width:
            lines.append(current.rstrip())
            current = "  "
        current += token + " "
    if current.strip():
        lines.append(current.rstrip())
    lines.append("]")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    raw = args.source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(f"unexpected archive SHA-256: {digest}")
    data = json.loads(gzip.decompress(raw))
    lower = data["farkas_0315305"]
    record = data["double_root_constructions"]["20"]
    if lower["source_weight_sha256"] != EXPECTED_WEIGHT_SHA256:
        raise SystemExit("unexpected lower-certificate weight hash")
    if list(map(int, lower["basis_degrees"])) != list(range(0, 84, 2)):
        raise SystemExit("unexpected lower-certificate basis")
    if list(map(int, record["basis_degrees"])) != list(range(0, 84, 2)):
        raise SystemExit("unexpected upper-witness basis")

    def primitive_integer_coefficients(values: list[str]) -> list[int]:
        rationals = list(map(Fraction, values))
        denominator = functools.reduce(math.lcm, (q.denominator for q in rationals))
        integers = [q.numerator * (denominator // q.denominator) for q in rationals]
        common = functools.reduce(math.gcd, integers)
        return [z // common for z in integers]

    primitive = primitive_integer_coefficients(record["residual_coefficients_ascending"])
    laguerre_primitive = primitive_integer_coefficients(record["laguerre_coefficients"])
    if primitive[0] <= 0 or primitive[-1] >= 0:
        raise SystemExit("unexpected primitive residual orientation")

    intervals: list[tuple[Fraction, Fraction]] = []
    span = Fraction(500) - RIGHT
    for index, depth in INTERVAL_LEAVES:
        a = RIGHT + span * Fraction(index, 2**depth)
        b = RIGHT + span * Fraction(index + 1, 2**depth)
        intervals.append((a, b))
    if intervals[0][0] != RIGHT or intervals[-1][1] != 500:
        raise SystemExit("interval cover has wrong endpoints")
    if any(intervals[i][1] != intervals[i + 1][0] for i in range(len(intervals) - 1)):
        raise SystemExit("interval cover is not contiguous")

    weight_rationals = list(map(Fraction, lower["weights"]))
    weight_denominator = functools.reduce(math.lcm, (q.denominator for q in weight_rationals))
    integer_weights = [q.numerator * (weight_denominator // q.denominator) for q in weight_rationals]
    weight_common = functools.reduce(math.gcd, integer_weights)
    integer_weights = [z // weight_common for z in integer_weights]
    certificate_value = Fraction(weight_denominator, weight_common)
    if any(z <= 0 for z in integer_weights):
        raise SystemExit("certificate weights are not positive")

    pieces = [
        "/- Generated by scripts/generate_certificate.py from the authenticated artifact. -/\n"
        "import Mathlib.Data.Rat.Defs\n\nnamespace UncertaintyS2.CertificateData",
        wrapped_array("nodes", [lean_rat(x) for x in lower["nodes"]]),
        wrapped_array("weights", [f"({z} : ℚ)" for z in integer_weights]),
        "def certificateValue : ℚ := " + lean_rat(certificate_value),
        wrapped_array("roots", [lean_rat(x) for x in record["root_rationals"]]),
        wrapped_array("residualCoefficients", [f"({z} : ℚ)" for z in primitive]),
        wrapped_array("laguerreCoefficients", [f"({z} : ℚ)" for z in laguerre_primitive]),
        "def isolatingLeft : ℚ := " + lean_rat(LEFT),
        "def isolatingRight : ℚ := " + lean_rat(RIGHT),
        "def tailIntervals : Array (ℚ × ℚ) := #[\n  "
        + ",\n  ".join(f"({lean_rat(a)}, {lean_rat(b)})" for a, b in intervals)
        + "\n]",
        f'def archiveSHA256 : String := "{EXPECTED_SHA256}"',
        f'def weightSHA256 : String := "{EXPECTED_WEIGHT_SHA256}"',
        "end UncertaintyS2.CertificateData\n",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n\n".join(pieces))


if __name__ == "__main__":
    main()
