#!/usr/bin/env python3
"""Generate exact rational Lean data from the four certificate TSV files."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path


@dataclass(frozen=True)
class Row:
    header: tuple[str, str, str]
    atoms: tuple[tuple[str, str, str], ...]


def decimal(text: str) -> Decimal:
    try:
        return Decimal(text)
    except InvalidOperation as exc:
        raise ValueError(f"not a decimal literal: {text!r}") from exc


def read_row(path: Path) -> Row:
    lines = [line.split() for line in path.read_text(encoding="ascii").splitlines()]
    if not lines or len(lines[0]) != 4:
        raise ValueError(f"{path}: malformed header")
    a0, a1, a2, count_text = lines[0]
    for value in (a0, a1, a2):
        decimal(value)
    count = int(count_text)
    atoms: list[tuple[str, str, str]] = []
    for line_number, fields in enumerate(lines[1:], start=2):
        if len(fields) != 3:
            raise ValueError(f"{path}:{line_number}: expected three columns")
        frequency, alpha, beta = fields
        for value in fields:
            decimal(value)
        if decimal(alpha) <= 0:
            raise ValueError(f"{path}:{line_number}: alpha is not positive")
        atoms.append((frequency, alpha, beta))
    if len(atoms) != count:
        raise ValueError(f"{path}: header says {count} atoms, found {len(atoms)}")
    return Row((a0, a1, a2), tuple(atoms))


def generate(rows: list[Row]) -> str:
    out = [
        "import ErdosMinimum.NumericRow",
        "",
        "/-!",
        "# Exact rational data for the four directed certificate rows",
        "",
        "This file is generated by `certificate/generate_lean_data.py` from the",
        "checked-in TSV payloads. Every decimal is elaborated as an exact rational;",
        "certificate replay therefore does not parse external files at theorem time.",
        "-/",
        "",
        "namespace ErdosMinimum.CertificateData",
        "",
    ]
    for index, row in enumerate(rows):
        a0, a1, a2 = row.header
        count = len(row.atoms)
        out.extend(
            [
                "set_option maxRecDepth 100000 in",
                f"def row{index}AtomVector : Vector RatAtom {count} := #v[",
            ]
        )
        out.extend(
            f"  ⟨{frequency}, {alpha}, {beta}⟩," for frequency, alpha, beta in row.atoms
        )
        out.extend(
            [
                "]",
                "",
                f"def row{index}AtomList : List RatAtom := row{index}AtomVector.toList",
                "",
                f"def row{index} : RatRow where",
                f"  a0 := {a0}",
                f"  a1 := {a1}",
                f"  a2 := {a2}",
                f"  atoms := row{index}AtomList",
                "",
            ]
        )
        if index == 0:
            out.extend(
                [
                    "/-- A cleaner symmetric version of the first dual row.  Its cosine",
                    "coefficients are unchanged, while the numerically negligible sine",
                    "coefficients and linear term are set to zero.  The dual theorem permits this",
                    "independent row, and its numerical obligations are replayed separately. -/",
                    "def row0Symmetric : RatRow where",
                    f"  a0 := {a0}",
                    "  a1 := 0",
                    f"  a2 := {a2}",
                    "  atoms := row0AtomList.map fun atom => { atom with beta := 0 }",
                    "",
                ]
            )
        out.extend(
            [
                f"def row{index}Atoms : Fin {count} → RatAtom := row{index}AtomVector.get",
                "",
                f"def row{index}DualAtoms : Fin {count} → ErdosMinimum.DualAtom :=",
                f"  fun i ↦ (row{index}Atoms i).toDual",
                "",
                f"theorem row{index}_vector_count : row{index}AtomVector.size = {count} := by rfl",
                "",
                "set_option maxRecDepth 100000 in",
                f"theorem row{index}_atom_count : row{index}.atoms.length = {count} := by rfl",
                "",
                "set_option maxRecDepth 100000 in",
                "set_option maxHeartbeats 0 in",
                f"theorem row{index}_alpha_pos (i : Fin {count}) : 0 < (row{index}Atoms i).alpha := by",
                "  revert i",
                "  decide +kernel",
                "",
                f"theorem row{index}_dual_alpha_pos (i : Fin {count}) :",
                f"    0 < (row{index}DualAtoms i).alpha := by",
                f"  simpa only [row{index}DualAtoms, RatAtom.toDual] using",
                f"    (Rat.cast_pos (K := ℝ)).2 (row{index}_alpha_pos i)",
                "",
            ]
        )
    counts = [len(row.atoms) for row in rows]
    out.extend(
        [
            "/-- Atom count indexed by the certificate row. -/",
            "def atomCount : Fin 4 → ℕ",
            *[f"  | {i} => {count}" for i, count in enumerate(counts)],
            "",
            "/-- The complete exact-rational certificate row. -/",
            "def row : Fin 4 → RatRow",
            *[f"  | {i} => row{i}" for i in range(4)],
            "",
            "/-- Exact atom data, with the row-dependent count in its type. -/",
            "def atoms : (row : Fin 4) → Fin (atomCount row) → RatAtom",
            *[f"  | {i} => row{i}Atoms" for i in range(4)],
            "",
            "/-- Analytic atom data, with exact rational values coerced to reals. -/",
            "def dualAtoms : (row : Fin 4) → Fin (atomCount row) → ErdosMinimum.DualAtom",
            *[f"  | {i} => row{i}DualAtoms" for i in range(4)],
            "",
            "/-- Every alpha in every row is strictly positive. -/",
            "theorem alpha_pos (row : Fin 4) (i : Fin (atomCount row)) :",
            "    0 < (atoms row i).alpha := by",
            "  fin_cases row",
            *[f"  exact row{i}_alpha_pos i" for i in range(4)],
            "",
            "/-- The real-valued analytic view preserves strict alpha positivity. -/",
            "theorem dual_alpha_pos (row : Fin 4) (i : Fin (atomCount row)) :",
            "    0 < (dualAtoms row i).alpha := by",
            "  fin_cases row",
            *[f"  exact row{i}_dual_alpha_pos i" for i in range(4)],
            "",
            "end ErdosMinimum.CertificateData",
            "",
        ]
    )
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--certificate-dir", type=Path, default=Path(__file__).resolve().parent
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "ErdosMinimum" / "CertificateData.lean",
    )
    args = parser.parse_args()
    rows = [read_row(args.certificate_dir / f"row{i}.tsv") for i in range(4)]
    args.output.write_text(generate(rows), encoding="utf-8")


if __name__ == "__main__":
    main()
