#!/usr/bin/env python3
"""Generate the exact Lean certificate data used by the 0.3089 proof."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from fractions import Fraction
from pathlib import Path


EXPECTED_ARCHIVE_SHA256 = (
    "04440bb9d0239a68ed38b7d780462380c2b698fdf54f0917c628ff7df35b9826"
)
EXPECTED_COEFFICIENT_SHA256 = (
    "8df170dcfc89ea3f707c16d22aab20f12939426e88bef117d6a9053cf46a3e16"
)

# Exact dyadic cover produced by the verification notebook, with adjacent
# endpoints shared literally. Exact recomputation gives every Bernstein
# coefficient < -1/100000 on each interval.
INTERVALS = [
    ("1213/625", "3108011/1280000"),
    ("3108011/1280000", "1865899/640000"),
    ("1865899/640000", "1244843/320000"),
    ("1244843/320000", "186863/32000"),
    ("186863/32000", "4361047/640000"),
    ("4361047/640000", "2492417/320000"),
    ("2492417/320000", "779051/80000"),
    ("779051/80000", "701419/40000"),
    ("701419/40000", "16213/640"),
    ("16213/640", "4677037/160000"),
    ("4677037/160000", "662603/20000"),
    ("662603/20000", "1948993/40000"),
    ("1948993/40000", "128639/2000"),
    ("128639/2000", "1910177/20000"),
    ("1910177/20000", "633491/5000"),
    ("633491/5000", "3157751/20000"),
    ("3157751/20000", "1890769/10000"),
    ("1890769/10000", "176213/800"),
    ("176213/800", "628639/2500"),
    ("628639/2500", "3138343/10000"),
    ("3138343/10000", "376213/1000"),
    ("376213/1000", "4385917/10000"),
    ("4385917/10000", "626213/1250"),
    ("626213/1250", "5633491/10000"),
    ("5633491/10000", "3128639/5000"),
    ("3128639/5000", "1876213/2500"),
    ("1876213/2500", "1000"),
]


def lean_rat(value: str) -> str:
    q = Fraction(value)
    if q.denominator == 1:
        return f"({q.numerator} : ℚ)"
    return f"({q.numerator} : ℚ) / {q.denominator}"


def wrapped_array(name: str, values: list[str], width: int = 92) -> str:
    lines = [f"def {name} : Array ℚ := #["]
    current = "  "
    for i, value in enumerate(values):
        token = value + ("," if i + 1 < len(values) else "")
        if len(current) > 2 and len(current) + len(token) + 1 > width:
            lines.append(current.rstrip())
            current = "  "
        current += token + " "
    if current.strip():
        lines.append(current.rstrip())
    lines.append("]")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    raw = args.source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_ARCHIVE_SHA256:
        raise SystemExit(f"unexpected archive SHA-256: {digest}")
    data = json.loads(gzip.decompress(raw))
    continuum = data["continuum"]
    if continuum["source_coefficient_sha256"] != EXPECTED_COEFFICIENT_SHA256:
        raise SystemExit("unexpected coefficient SHA-256")
    if continuum["basis_degrees"] != list(range(0, 228, 2)):
        raise SystemExit("unexpected Laguerre basis")

    laguerre = [lean_rat(x) for x in continuum["laguerre_coefficients"]]
    power = [lean_rat(x) for x in continuum["power_coefficients_ascending"]]
    interval_values = [
        f"({lean_rat(left)}, {lean_rat(right)})" for left, right in INTERVALS
    ]

    generated = "\n\n".join(
        [
            "/- This file is generated by scripts/generate_certificate.py. -/\n"
            "import Mathlib.Data.Rat.Defs\n\n"
            "namespace UncertaintyUpperBound.CertificateData",
            wrapped_array("laguerreCoefficients", laguerre),
            wrapped_array("powerCoefficients", power),
            "def intervals : Array (ℚ × ℚ) := #[\n  "
            + ",\n  ".join(interval_values)
            + "\n]",
            'def archiveSHA256 : String := "' + EXPECTED_ARCHIVE_SHA256 + '"',
            'def coefficientSHA256 : String := "'
            + EXPECTED_COEFFICIENT_SHA256
            + '"',
            "end UncertaintyUpperBound.CertificateData\n",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)


if __name__ == "__main__":
    main()
